#!/usr/bin/env node

'use strict';

var fs         = require('fs')
  , browserify = require('browserify')
  , es6ify     = require('es6ify')
  , uglifyify  = require('uglifyify')
  , program    = require('commander')
  , brfs       = require('brfs')

function run(source, dest) {

  var bundler = browserify({ debug: !!program.debug })

  if (program.es6) {
    bundler = bundler
      .add(es6ify.runtime)
      .transform(es6ify)
  }

  if (program.brfs) {
    bundler = bundler
      .transform(brfs)
  }

  if (program.minify) bundler = bundler.transform(uglifyify)

  bundler
    .require(require.resolve(source), { entry: true })
    .bundle()
    .on('error', function (err) { console.error(err) })
    .pipe(fs.createWriteStream(dest))
    .on('finish', function () {
      console.log('bundle file built successfully')
    })
}

program
  .version('0.0.1')
  .option('-e, --es6', 'Transform es6 code to es5 using traceur')
  .option('-d, --debug', 'Include source files')
  .option('-m, --minify', 'Minify the resulting bundle')
  .option('-b, --brfs', 'Use brfs transform')

program
  .command('*')
  .action(run)

program
  .parse(process.argv)
